# Generated by Django 5.1.2 on 2024-10-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('contactno', models.CharField(max_length=15)),
                ('enqtext', models.CharField(max_length=500)),
                ('regdate', models.DateTimeField()),
            ],
        ),
    ]
