# Generated by Django 5.1.2 on 2024-10-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biotech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('contactno', models.CharField(max_length=15)),
                ('enqtext', models.CharField(max_length=500)),
                ('regdate', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
