# Generated by Django 5.0.6 on 2024-11-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biotech', '0003_course_login_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=14)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
