# Generated by Django 5.0.6 on 2024-11-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biotech', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=14)),
                ('password', models.CharField(max_length=16)),
                ('fname', models.CharField(max_length=200)),
                ('mname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('addharno', models.IntegerField()),
                ('addharpic', models.FileField(upload_to='Docment_verification')),
                ('session', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=200)),
                ('course_duration', models.CharField(max_length=100)),
                ('hs_percent', models.CharField(max_length=10)),
                ('hs_marksheet', models.FileField(upload_to='Docment_verification')),
                ('inter_percent', models.CharField(max_length=10)),
                ('inter_marksheet', models.FileField(upload_to='Docment_verification')),
                ('profile_pic', models.FileField(upload_to='Docment_verification')),
                ('sing', models.FileField(upload_to='Docment_verification')),
                ('form_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
