# Generated by Django 5.0.6 on 2024-11-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biotech', '0005_tbl_student_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_student',
            name='addharno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='addharpic',
            field=models.FileField(null=True, upload_to='Docment_verification'),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='course',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='course_duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='fname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='form_status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='hs_marksheet',
            field=models.FileField(null=True, upload_to='Docment_verification'),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='hs_percent',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='inter_marksheet',
            field=models.FileField(null=True, upload_to='Docment_verification'),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='inter_percent',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='mname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='Docment_verification'),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='session',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='sing',
            field=models.FileField(null=True, upload_to='Docment_verification'),
        ),
    ]
