# Generated by Django 5.0.6 on 2024-11-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biotech', '0006_alter_tbl_student_addharno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_student',
            name='course_fees',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
