# Generated by Django 5.0.6 on 2024-11-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biotech', '0007_tbl_student_course_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('fees', models.CharField(max_length=20)),
                ('fees_status', models.CharField(max_length=50)),
                ('fees_sc', models.FileField(null=True, upload_to='myimage')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
