# Generated by Django 5.0.6 on 2024-11-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biotech', '0008_fees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fees',
        ),
        migrations.AddField(
            model_name='tbl_student',
            name='fees',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_student',
            name='fees_sc',
            field=models.FileField(null=True, upload_to='myimage'),
        ),
        migrations.AddField(
            model_name='tbl_student',
            name='fees_status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
