# Generated by Django 5.0.6 on 2024-12-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biotech', '0009_delete_fees_tbl_student_fees_tbl_student_fees_sc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
