# Generated by Django 5.0.6 on 2024-12-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biotech', '0010_alter_session_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(max_length=15),
        ),
    ]
